# Generated by Django 3.0.3 on 2020-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('tests', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='my_extra_field',
            field=models.TextField(default=''),
            preserve_default=False,
        )
    ]
